version: '3.8'

services:

  feedback-app:
    build: ./
    # build:
    #   context: ./
    #   dockerfile: Dockerfile
    container_name: feedback-app
    hostname: feedback-app
    volumes:
      - feedback:/app/feedback
      - .:/app
      - /app/node_modules
    ports:
      - 80:80

volumes:
  feedback:
